#!/bin/sh

start() {
  mount -t debugfs none /sys/kernel/debug
}

stop() {
  umount /sys/kernel/debug
  sleep 1
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

